# Generated by Django 6.1 on 2026-08-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                default="messages",
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.conversation",
            ),
        ),
    ]
